services:
  devcontainer:
    build:
      context: .
      args:
        UID: "${UID}"
      dockerfile: dockerfile.alpine
    container_name: "${PROJNAME}"
    ports:
      - 127.0.0.1:${PROJPORT}:22
    volumes:
      - alpine-includes:/usr/includes/
volumes:
  alpine-includes:
